/*
 * Generated by BeChicken
 * on 11/13/2019
 * version v1.0
 */
(function () {
    cc.PhoenixPopupView = cc.Class({
        "extends": cc.PopupViewBase,
        properties: {
            // prefabHelp / prefabTop / prefabHistory (va create*/destroy* tuong ung) DA CO SAN
            // o lop cha PopupViewBase - KHONG khai bao lai o day (se bao "hides inherited property").
            prefabGraph: cc.Prefab,
			prefabJpHistory: cc.Prefab,
            // KHONG co trong PopupViewBase (base chi co Help/History/Top/BetLines/SessionDetail) -> khai bao o day.
            prefabUserInRoom: cc.Prefab
        },
		
        onLoad: function () {
            cc.PhoenixPopupController.getInstance().setPopupView(this);
        },
		
        createGraphView: function () {
            this.nodeGraph = this.createView(this.prefabGraph);
        },
		
        destroyGraphView: function () {
            if (this.nodeGraph)
                this.nodeGraph.destroy();
        },
		
        createJpHistoryView: function () {
            this.nodeJpHistory = this.createView(this.prefabJpHistory);
        },

        destroyJpHistoryView: function () {
            if (this.nodeJpHistory)
                this.nodeJpHistory.destroy();
        },

        // Nguoi trong phong: view tu xin danh sach o onEnable (hub GetUserInRoom).
        createUserInRoomView: function () {
            if (!this.prefabUserInRoom) return;
            this.nodeUserInRoom = this.createView(this.prefabUserInRoom);
        },

        destroyUserInRoomView: function () {
            if (this.nodeUserInRoom)
                this.nodeUserInRoom.destroy();
        },
    });
}).call(this);